### ISSUE TITLE
Some issues with the "About" page

### ISSUE THREAD

**Issue by ahorjia** [googleinterns/step3-2020#70]
The top level headers "About us", "STEP Internship", and "Technology Stack" are h3 which is fine however
1. It is probably better if "STEP Internship" is not a link itself and instead somewhere in its description there is a link to the STEP program.
2. Same issue for "Dependencies" it is probably better not to have it directly as a link
3. The headers under "Technology Stack" are "h5" it might look better if we make them "h4" it will make the fonts look more proportional.
4. We probably don't need the ":" character at the end of the headers e.g. "Frontend" instead of "Frontend:"
5. Some of the image links are broken (https://screenshot.googleplex.com/Ek3M6hZwP5x)
6. Change this text "We obtained a list of names of nonprofits from Google for Nonprofits (G4NP). " to something like "WE obtained a list of names of nonprofits from IRS's publicly available list (with the link to the list)"
7. Linked link is broken for Iris and Elijah
8. When launching external links like GITHUB or LINKEDIN use target="_blank" to open it in a new tab
9. Instead of GITHUB use GitHub
10. Instead of LINKEDIN use LinkedIn

**Comment by tonypan2000** [comment]
11. Link to gson under dependency cannot be found, [bad link](https://lh3.googleusercontent.com/proxy/NropP4In0TraUsuAm_0SMBDWvJ_psgN88KKs9IYVBALXIMUi1rY8x1USGdZiUwu78YtuEWlySC49C6pjeWt0cCNPSQm_Sg4V0w-7IZqBJnI-nV4nCpgFY0KlOn1UFmcHbE95RVBIt3hv)
12. "A cookie associated with a cross-site resource at http://medium.com/ was set without the `SameSite` attribute. It has been blocked, as Chrome now only delivers cookies with cross-site requests if they are set with `SameSite=None` and `Secure`. You can review cookies in developer tools under Application>Storage>Cookies and see more details at https://www.chromestatus.com/feature/5088147346030592 and https://www.chromestatus.com/feature/5633521622188032."
I am guessing some of the images are taken from other websites?
